list(APPEND ICONS_SRC
    material/index.theme
    material/svg/3d-rotation.svg
    material/svg/access-alarms.svg
    material/svg/access-alarm.svg
    material/svg/accessibility.svg
    material/svg/accessible.svg
    material/svg/access-time.svg
    material/svg/account-balance.svg
    material/svg/account-balance-wallet.svg
    material/svg/account-box.svg
    material/svg/account-circle.svg
    material/svg/ac-unit.svg
    material/svg/adb.svg
    material/svg/add-alarm.svg
    material/svg/add-alert.svg
    material/svg/add-box.svg
    material/svg/add-circle-outline.svg
    material/svg/add-circle.svg
    material/svg/add-location.svg
    material/svg/add-shopping-cart.svg
    material/svg/add.svg
    material/svg/add-to-photos.svg
    material/svg/add-to-queue.svg
    material/svg/adjust.svg
    material/svg/airline-seat-flat-angled.svg
    material/svg/airline-seat-flat.svg
    material/svg/airline-seat-individual-suite.svg
    material/svg/airline-seat-legroom-extra.svg
    material/svg/airline-seat-legroom-normal.svg
    material/svg/airline-seat-legroom-reduced.svg
    material/svg/airline-seat-recline-extra.svg
    material/svg/airline-seat-recline-normal.svg
    material/svg/airplanemode-active.svg
    material/svg/airplanemode-inactive.svg
    material/svg/airplay.svg
    material/svg/airport-shuttle.svg
    material/svg/alarm-add.svg
    material/svg/alarm-off.svg
    material/svg/alarm-on.svg
    material/svg/alarm.svg
    material/svg/album.svg
    material/svg/all-inclusive.svg
    material/svg/all-out.svg
    material/svg/android.svg
    material/svg/announcement.svg
    material/svg/apps.svg
    material/svg/archive.svg
    material/svg/arrow-back.svg
    material/svg/arrow-downward.svg
    material/svg/arrow-drop-down-circle.svg
    material/svg/arrow-drop-down.svg
    material/svg/arrow-drop-up.svg
    material/svg/arrow-forward.svg
    material/svg/arrow-upward.svg
    material/svg/art-track.svg
    material/svg/aspect-ratio.svg
    material/svg/assessment.svg
    material/svg/assignment-ind.svg
    material/svg/assignment-late.svg
    material/svg/assignment-returned.svg
    material/svg/assignment-return.svg
    material/svg/assignment.svg
    material/svg/assignment-turned-in.svg
    material/svg/assistant-photo.svg
    material/svg/assistant.svg
    material/svg/attach-file.svg
    material/svg/attachment.svg
    material/svg/attach-money.svg
    material/svg/audiotrack.svg
    material/svg/autorenew.svg
    material/svg/av-timer.svg
    material/svg/backspace.svg
    material/svg/backup.svg
    material/svg/battery-20.svg
    material/svg/battery-30.svg
    material/svg/battery-50.svg
    material/svg/battery-60.svg
    material/svg/battery-80.svg
    material/svg/battery-90.svg
    material/svg/battery-alert.svg
    material/svg/battery-charging-20.svg
    material/svg/battery-charging-30.svg
    material/svg/battery-charging-50.svg
    material/svg/battery-charging-60.svg
    material/svg/battery-charging-80.svg
    material/svg/battery-charging-90.svg
    material/svg/battery-charging-full.svg
    material/svg/battery-full.svg
    material/svg/battery-std.svg
    material/svg/battery-unknown.svg
    material/svg/beach-access.svg
    material/svg/beenhere.svg
    material/svg/block.svg
    material/svg/bluetooth-audio.svg
    material/svg/bluetooth-connected.svg
    material/svg/bluetooth-disabled.svg
    material/svg/bluetooth-searching.svg
    material/svg/bluetooth.svg
    material/svg/blur-circular.svg
    material/svg/blur-linear.svg
    material/svg/blur-off.svg
    material/svg/blur-on.svg
    material/svg/bookmark-border.svg
    material/svg/bookmark.svg
    material/svg/book.svg
    material/svg/border-all.svg
    material/svg/border-bottom.svg
    material/svg/border-clear.svg
    material/svg/border-color.svg
    material/svg/border-horizontal.svg
    material/svg/border-inner.svg
    material/svg/border-left.svg
    material/svg/border-outer.svg
    material/svg/border-right.svg
    material/svg/border-style.svg
    material/svg/border-top.svg
    material/svg/border-vertical.svg
    material/svg/branding-watermark.svg
    material/svg/brightness-1.svg
    material/svg/brightness-2.svg
    material/svg/brightness-3.svg
    material/svg/brightness-4.svg
    material/svg/brightness-5.svg
    material/svg/brightness-6.svg
    material/svg/brightness-7.svg
    material/svg/brightness-auto.svg
    material/svg/brightness-high.svg
    material/svg/brightness-low.svg
    material/svg/brightness-medium.svg
    material/svg/broken-image.svg
    material/svg/brush.svg
    material/svg/bubble-chart.svg
    material/svg/bug-report.svg
    material/svg/build.svg
    material/svg/burst-mode.svg
    material/svg/business-center.svg
    material/svg/business.svg
    material/svg/cached.svg
    material/svg/cake.svg
    material/svg/call-end.svg
    material/svg/call-made.svg
    material/svg/call-merge.svg
    material/svg/call-missed-outgoing.svg
    material/svg/call-missed.svg
    material/svg/call-received.svg
    material/svg/call-split.svg
    material/svg/call.svg
    material/svg/call-to-action.svg
    material/svg/camera-alt.svg
    material/svg/camera-front.svg
    material/svg/camera-rear.svg
    material/svg/camera-roll.svg
    material/svg/camera.svg
    material/svg/cancel.svg
    material/svg/card-giftcard.svg
    material/svg/card-membership.svg
    material/svg/card-travel.svg
    material/svg/casino.svg
    material/svg/cast-connected.svg
    material/svg/cast.svg
    material/svg/center-focus-strong.svg
    material/svg/center-focus-weak.svg
    material/svg/change-history.svg
    material/svg/chat-bubble-outline.svg
    material/svg/chat-bubble.svg
    material/svg/chat.svg
    material/svg/check-box-outline-blank.svg
    material/svg/check-box.svg
    material/svg/check-circle.svg
    material/svg/check.svg
    material/svg/chevron-left.svg
    material/svg/chevron-right.svg
    material/svg/child-care.svg
    material/svg/child-friendly.svg
    material/svg/chrome-reader-mode.svg
    material/svg/class.svg
    material/svg/clear-all.svg
    material/svg/clear.svg
    material/svg/closed-caption.svg
    material/svg/close.svg
    material/svg/cloud-circle.svg
    material/svg/cloud-done.svg
    material/svg/cloud-download.svg
    material/svg/cloud-off.svg
    material/svg/cloud-queue.svg
    material/svg/cloud.svg
    material/svg/cloud-upload.svg
    material/svg/code.svg
    material/svg/collections.svg
    material/svg/colorize.svg
    material/svg/color-lens.svg
    material/svg/comment.svg
    material/svg/compare-arrows.svg
    material/svg/compare.svg
    material/svg/computer.svg
    material/svg/confirmation-number.svg
    material/svg/contact-mail.svg
    material/svg/contact-phone.svg
    material/svg/contacts.svg
    material/svg/content-copy.svg
    material/svg/content-cut.svg
    material/svg/content-paste.svg
    material/svg/control-point-duplicate.svg
    material/svg/control-point.svg
    material/svg/copyright.svg
    material/svg/create-new-folder.svg
    material/svg/create.svg
    material/svg/credit-card.svg
    material/svg/crop-16-9.svg
    material/svg/crop-3-2.svg
    material/svg/crop-5-4.svg
    material/svg/crop-7-5.svg
    material/svg/crop-din.svg
    material/svg/crop-free.svg
    material/svg/crop-landscape.svg
    material/svg/crop-original.svg
    material/svg/crop-portrait.svg
    material/svg/crop-rotate.svg
    material/svg/crop-square.svg
    material/svg/crop.svg
    material/svg/dashboard.svg
    material/svg/data-usage.svg
    material/svg/date-range.svg
    material/svg/dehaze.svg
    material/svg/delete-forever.svg
    material/svg/delete.svg
    material/svg/delete-sweep.svg
    material/svg/description.svg
    material/svg/desktop-mac.svg
    material/svg/desktop-windows.svg
    material/svg/details.svg
    material/svg/developer-board.svg
    material/svg/developer-mode.svg
    material/svg/devices-other.svg
    material/svg/devices.svg
    material/svg/dialer-sip.svg
    material/svg/dialpad.svg
    material/svg/directions-bike.svg
    material/svg/directions-boat.svg
    material/svg/directions-bus.svg
    material/svg/directions-car.svg
    material/svg/directions-railway.svg
    material/svg/directions-run.svg
    material/svg/directions-subway.svg
    material/svg/directions.svg
    material/svg/directions-transit.svg
    material/svg/directions-walk.svg
    material/svg/disc-full.svg
    material/svg/dns.svg
    material/svg/dock.svg
    material/svg/domain.svg
    material/svg/done-all.svg
    material/svg/done.svg
    material/svg/do-not-disturb-alt.svg
    material/svg/do-not-disturb-off.svg
    material/svg/do-not-disturb-on.svg
    material/svg/do-not-disturb.svg
    material/svg/donut-large.svg
    material/svg/donut-small.svg
    material/svg/drafts.svg
    material/svg/drag-handle.svg
    material/svg/drag-indicator.svg
    material/svg/drive-eta.svg
    material/svg/dvr.svg
    material/svg/edit-location.svg
    material/svg/edit.svg
    material/svg/email.svg
    material/svg/enhanced-encryption.svg
    material/svg/equalizer.svg
    material/svg/error-outline.svg
    material/svg/error.svg
    material/svg/euro-symbol.svg
    material/svg/event-available.svg
    material/svg/event-busy.svg
    material/svg/event-note.svg
    material/svg/event-seat.svg
    material/svg/event.svg
    material/svg/ev-station.svg
    material/svg/exit-to-app.svg
    material/svg/expand-less.svg
    material/svg/expand-more.svg
    material/svg/explicit.svg
    material/svg/explore.svg
    material/svg/exposure-neg-1.svg
    material/svg/exposure-neg-2.svg
    material/svg/exposure-plus-1.svg
    material/svg/exposure-plus-2.svg
    material/svg/exposure.svg
    material/svg/exposure-zero.svg
    material/svg/extension.svg
    material/svg/face.svg
    material/svg/fast-forward.svg
    material/svg/fast-rewind.svg
    material/svg/favorite-border.svg
    material/svg/favorite.svg
    material/svg/featured-play-list.svg
    material/svg/featured-video.svg
    material/svg/feedback.svg
    material/svg/fiber-dvr.svg
    material/svg/fiber-manual-record.svg
    material/svg/fiber-new.svg
    material/svg/fiber-pin.svg
    material/svg/fiber-smart-record.svg
    material/svg/file-download.svg
    material/svg/file-upload.svg
    material/svg/filter-1.svg
    material/svg/filter-2.svg
    material/svg/filter-3.svg
    material/svg/filter-4.svg
    material/svg/filter-5.svg
    material/svg/filter-6.svg
    material/svg/filter-7.svg
    material/svg/filter-8.svg
    material/svg/filter-9-plus.svg
    material/svg/filter-9.svg
    material/svg/filter-b-and-w.svg
    material/svg/filter-center-focus.svg
    material/svg/filter-drama.svg
    material/svg/filter-frames.svg
    material/svg/filter-hdr.svg
    material/svg/filter-list.svg
    material/svg/filter-none.svg
    material/svg/filter.svg
    material/svg/filter-tilt-shift.svg
    material/svg/filter-vintage.svg
    material/svg/find-in-page.svg
    material/svg/find-replace.svg
    material/svg/fingerprint.svg
    material/svg/first-page.svg
    material/svg/fitness-center.svg
    material/svg/flag.svg
    material/svg/flare.svg
    material/svg/flash-auto.svg
    material/svg/flash-off.svg
    material/svg/flash-on.svg
    material/svg/flight-land.svg
    material/svg/flight.svg
    material/svg/flight-takeoff.svg
    material/svg/flip.svg
    material/svg/flip-to-back.svg
    material/svg/flip-to-front.svg
    material/svg/folder-open.svg
    material/svg/folder-shared.svg
    material/svg/folder-special.svg
    material/svg/folder.svg
    material/svg/format-align-center.svg
    material/svg/format-align-justify.svg
    material/svg/format-align-left.svg
    material/svg/format-align-right.svg
    material/svg/format-bold.svg
    material/svg/format-clear.svg
    material/svg/format-color-fill.svg
    material/svg/format-color-reset.svg
    material/svg/format-color-text.svg
    material/svg/format-indent-decrease.svg
    material/svg/format-indent-increase.svg
    material/svg/format-italic.svg
    material/svg/format-line-spacing.svg
    material/svg/format-list-bulleted.svg
    material/svg/format-list-numbered.svg
    material/svg/format-paint.svg
    material/svg/format-quote.svg
    material/svg/format-shapes.svg
    material/svg/format-size.svg
    material/svg/format-strikethrough.svg
    material/svg/format-textdirection-l-to-r.svg
    material/svg/format-textdirection-r-to-l.svg
    material/svg/format-underlined.svg
    material/svg/forum.svg
    material/svg/forward-10.svg
    material/svg/forward-30.svg
    material/svg/forward-5.svg
    material/svg/forward.svg
    material/svg/free-breakfast.svg
    material/svg/fullscreen-exit.svg
    material/svg/fullscreen.svg
    material/svg/functions.svg
    material/svg/gamepad.svg
    material/svg/games.svg
    material/svg/gavel.svg
    material/svg/gesture.svg
    material/svg/get-app.svg
    material/svg/golf-course.svg
    material/svg/gps-fixed.svg
    material/svg/gps-not-fixed.svg
    material/svg/gps-off.svg
    material/svg/grade.svg
    material/svg/gradient.svg
    material/svg/grain.svg
    material/svg/graphic-eq.svg
    material/svg/grid-off.svg
    material/svg/grid-on.svg
    material/svg/group-add.svg
    material/svg/group.svg
    material/svg/group-work.svg
    material/svg/g-translate.svg
    material/svg/hdr-off.svg
    material/svg/hdr-on.svg
    material/svg/hdr-strong.svg
    material/svg/hdr-weak.svg
    material/svg/headset-mic.svg
    material/svg/headset.svg
    material/svg/healing.svg
    material/svg/hearing.svg
    material/svg/help.svg
    material/svg/highlight-off.svg
    material/svg/highlight.svg
    material/svg/high-quality.svg
    material/svg/history.svg
    material/svg/home.svg
    material/svg/hotel.svg
    material/svg/hot-tub.svg
    material/svg/hourglass-empty.svg
    material/svg/hourglass-full.svg
    material/svg/https.svg
    material/svg/http.svg
    material/svg/image-aspect-ratio.svg
    material/svg/image.svg
    material/svg/important-devices.svg
    material/svg/import-contacts.svg
    material/svg/import-export.svg
    material/svg/inbox.svg
    material/svg/info-outline.svg
    material/svg/info.svg
    material/svg/input.svg
    material/svg/insert-chart.svg
    material/svg/insert-comment.svg
    material/svg/insert-drive-file.svg
    material/svg/insert-emoticon.svg
    material/svg/insert-invitation.svg
    material/svg/insert-link.svg
    material/svg/insert-photo.svg
    material/svg/invert-colors-off.svg
    material/svg/invert-colors.svg
    material/svg/iso.svg
    material/svg/keyboard-arrow-down.svg
    material/svg/keyboard-arrow-left.svg
    material/svg/keyboard-arrow-right.svg
    material/svg/keyboard-arrow-up.svg
    material/svg/keyboard-backspace.svg
    material/svg/keyboard-capslock.svg
    material/svg/keyboard-hide.svg
    material/svg/keyboard-return.svg
    material/svg/keyboard.svg
    material/svg/keyboard-tab.svg
    material/svg/keyboard-voice.svg
    material/svg/kitchen.svg
    material/svg/label-outline.svg
    material/svg/label.svg
    material/svg/landscape.svg
    material/svg/language.svg
    material/svg/laptop-chromebook.svg
    material/svg/laptop-mac.svg
    material/svg/laptop.svg
    material/svg/laptop-windows.svg
    material/svg/last-page.svg
    material/svg/launch.svg
    material/svg/layers-clear.svg
    material/svg/layers.svg
    material/svg/leak-add.svg
    material/svg/leak-remove.svg
    material/svg/lens.svg
    material/svg/library-add.svg
    material/svg/library-books.svg
    material/svg/library-music.svg
    material/svg/lightbulb-outline.svg
    material/svg/linear-scale.svg
    material/svg/line-style.svg
    material/svg/line-weight.svg
    material/svg/linked-camera.svg
    material/svg/link.svg
    material/svg/list.svg
    material/svg/live-help.svg
    material/svg/live-tv.svg
    material/svg/local-activity.svg
    material/svg/local-airport.svg
    material/svg/local-atm.svg
    material/svg/local-bar.svg
    material/svg/local-cafe.svg
    material/svg/local-car-wash.svg
    material/svg/local-convenience-store.svg
    material/svg/local-dining.svg
    material/svg/local-drink.svg
    material/svg/local-florist.svg
    material/svg/local-gas-station.svg
    material/svg/local-grocery-store.svg
    material/svg/local-hospital.svg
    material/svg/local-hotel.svg
    material/svg/local-laundry-service.svg
    material/svg/local-library.svg
    material/svg/local-mall.svg
    material/svg/local-movies.svg
    material/svg/local-offer.svg
    material/svg/local-parking.svg
    material/svg/local-pharmacy.svg
    material/svg/local-phone.svg
    material/svg/local-pizza.svg
    material/svg/local-play.svg
    material/svg/local-post-office.svg
    material/svg/local-printshop.svg
    material/svg/local-see.svg
    material/svg/local-shipping.svg
    material/svg/local-taxi.svg
    material/svg/location-city.svg
    material/svg/location-disabled.svg
    material/svg/location-off.svg
    material/svg/location-on.svg
    material/svg/location-searching.svg
    material/svg/lock-open.svg
    material/svg/lock-outline.svg
    material/svg/lock.svg
    material/svg/looks-3.svg
    material/svg/looks-4.svg
    material/svg/looks-5.svg
    material/svg/looks-6.svg
    material/svg/looks-one.svg
    material/svg/looks.svg
    material/svg/looks-two.svg
    material/svg/loop.svg
    material/svg/loupe.svg
    material/svg/low-priority.svg
    material/svg/loyalty.svg
    material/svg/mail-outline.svg
    material/svg/mail.svg
    material/svg/map.svg
    material/svg/markunread-mailbox.svg
    material/svg/markunread.svg
    material/svg/memory.svg
    material/svg/menu.svg
    material/svg/merge-type.svg
    material/svg/message.svg
    material/svg/mic-none.svg
    material/svg/mic-off.svg
    material/svg/mic.svg
    material/svg/mms.svg
    material/svg/mode-comment.svg
    material/svg/mode-edit.svg
    material/svg/monetization-on.svg
    material/svg/monochrome-photos.svg
    material/svg/mood-bad.svg
    material/svg/mood.svg
    material/svg/more-horiz.svg
    material/svg/more.svg
    material/svg/more-vert.svg
    material/svg/motorcycle.svg
    material/svg/mouse.svg
    material/svg/move-to-inbox.svg
    material/svg/movie-creation.svg
    material/svg/movie-filter.svg
    material/svg/movie.svg
    material/svg/multiline-chart.svg
    material/svg/music-note.svg
    material/svg/music-video.svg
    material/svg/my-location.svg
    material/svg/nature-people.svg
    material/svg/nature.svg
    material/svg/navigate-before.svg
    material/svg/navigate-next.svg
    material/svg/navigation.svg
    material/svg/near-me.svg
    material/svg/network-cell.svg
    material/svg/network-check.svg
    material/svg/network-locked.svg
    material/svg/network-wifi.svg
    material/svg/new-releases.svg
    material/svg/next-week.svg
    material/svg/nfc.svg
    material/svg/no-encryption.svg
    material/svg/no-sim.svg
    material/svg/note-add.svg
    material/svg/note.svg
    material/svg/notifications-active.svg
    material/svg/notifications-none.svg
    material/svg/notifications-off.svg
    material/svg/notifications-paused.svg
    material/svg/notifications.svg
    material/svg/not-interested.svg
    material/svg/ondemand-video.svg
    material/svg/opacity.svg
    material/svg/open-in-browser.svg
    material/svg/open-in-new.svg
    material/svg/open-with.svg
    material/svg/pages.svg
    material/svg/pageview.svg
    material/svg/palette.svg
    material/svg/panorama-fish-eye.svg
    material/svg/panorama-horizontal.svg
    material/svg/panorama.svg
    material/svg/panorama-vertical.svg
    material/svg/panorama-wide-angle.svg
    material/svg/pan-tool.svg
    material/svg/party-mode.svg
    material/svg/pause-circle-filled.svg
    material/svg/pause-circle-outline.svg
    material/svg/pause.svg
    material/svg/payment.svg
    material/svg/people-outline.svg
    material/svg/people.svg
    material/svg/perm-camera-mic.svg
    material/svg/perm-contact-calendar.svg
    material/svg/perm-data-setting.svg
    material/svg/perm-device-information.svg
    material/svg/perm-identity.svg
    material/svg/perm-media.svg
    material/svg/perm-phone-msg.svg
    material/svg/perm-scan-wifi.svg
    material/svg/person-add.svg
    material/svg/personal-video.svg
    material/svg/person-outline.svg
    material/svg/person-pin-circle.svg
    material/svg/person-pin.svg
    material/svg/person.svg
    material/svg/pets.svg
    material/svg/phone-android.svg
    material/svg/phone-bluetooth-speaker.svg
    material/svg/phone-forwarded.svg
    material/svg/phone-in-talk.svg
    material/svg/phone-iphone.svg
    material/svg/phonelink-off.svg
    material/svg/phonelink.svg
    material/svg/phone-locked.svg
    material/svg/phone-missed.svg
    material/svg/phone-paused.svg
    material/svg/phone.svg
    material/svg/photo-album.svg
    material/svg/photo-camera.svg
    material/svg/photo-filter.svg
    material/svg/photo-library.svg
    material/svg/photo.svg
    material/svg/picture-as-pdf.svg
    material/svg/picture-in-picture-alt.svg
    material/svg/picture-in-picture.svg
    material/svg/pie-chart-outlined.svg
    material/svg/pie-chart.svg
    material/svg/pin-drop.svg
    material/svg/place.svg
    material/svg/play-arrow.svg
    material/svg/play-circle-filled.svg
    material/svg/play-circle-filled-white.svg
    material/svg/play-circle-outline.svg
    material/svg/play-for-work.svg
    material/svg/playlist-add-check.svg
    material/svg/playlist-add.svg
    material/svg/playlist-play.svg
    material/svg/plus-one.svg
    material/svg/poll.svg
    material/svg/polymer.svg
    material/svg/pool.svg
    material/svg/portable-wifi-off.svg
    material/svg/portrait.svg
    material/svg/power-input.svg
    material/svg/power-settings-new.svg
    material/svg/power.svg
    material/svg/pregnant-woman.svg
    material/svg/present-to-all.svg
    material/svg/print.svg
    material/svg/priority-high.svg
    material/svg/public.svg
    material/svg/publish.svg
    material/svg/query-builder.svg
    material/svg/question-answer.svg
    material/svg/queue-music.svg
    material/svg/queue-play-next.svg
    material/svg/queue.svg
    material/svg/radio-button-checked.svg
    material/svg/radio-button-unchecked.svg
    material/svg/radio.svg
    material/svg/rate-review.svg
    material/svg/receipt.svg
    material/svg/recent-actors.svg
    material/svg/record-voice-over.svg
    material/svg/redeem.svg
    material/svg/redo.svg
    material/svg/refresh.svg
    material/svg/remove-circle-outline.svg
    material/svg/remove-circle.svg
    material/svg/remove-from-queue.svg
    material/svg/remove-red-eye.svg
    material/svg/remove-shopping-cart.svg
    material/svg/remove.svg
    material/svg/repeat-one.svg
    material/svg/repeat.svg
    material/svg/replay-10.svg
    material/svg/replay-30.svg
    material/svg/replay-5.svg
    material/svg/replay.svg
    material/svg/reply-all.svg
    material/svg/reply.svg
    material/svg/report-problem.svg
    material/svg/report.svg
    material/svg/restaurant-menu.svg
    material/svg/restaurant.svg
    material/svg/restore-page.svg
    material/svg/restore.svg
    material/svg/ring-volume.svg
    material/svg/room-service.svg
    material/svg/room.svg
    material/svg/rotate-90-degrees-ccw.svg
    material/svg/rotate-left.svg
    material/svg/rotate-right.svg
    material/svg/rounded-corner.svg
    material/svg/router.svg
    material/svg/rowing.svg
    material/svg/rss-feed.svg
    material/svg/rv-hookup.svg
    material/svg/satellite.svg
    material/svg/save.svg
    material/svg/scanner.svg
    material/svg/schedule.svg
    material/svg/school.svg
    material/svg/screen-lock-landscape.svg
    material/svg/screen-lock-portrait.svg
    material/svg/screen-lock-rotation.svg
    material/svg/screen-rotation.svg
    material/svg/screen-share.svg
    material/svg/sd-card.svg
    material/svg/sd-storage.svg
    material/svg/search.svg
    material/svg/security.svg
    material/svg/select-all.svg
    material/svg/send.svg
    material/svg/sentiment-dissatisfied.svg
    material/svg/sentiment-neutral.svg
    material/svg/sentiment-satisfied.svg
    material/svg/sentiment-very-dissatisfied.svg
    material/svg/sentiment-very-satisfied.svg
    material/svg/settings-applications.svg
    material/svg/settings-backup-restore.svg
    material/svg/settings-bluetooth.svg
    material/svg/settings-brightness.svg
    material/svg/settings-cell.svg
    material/svg/settings-ethernet.svg
    material/svg/settings-input-antenna.svg
    material/svg/settings-input-component.svg
    material/svg/settings-input-composite.svg
    material/svg/settings-input-hdmi.svg
    material/svg/settings-input-svideo.svg
    material/svg/settings-overscan.svg
    material/svg/settings-phone.svg
    material/svg/settings-power.svg
    material/svg/settings-remote.svg
    material/svg/settings.svg
    material/svg/settings-system-daydream.svg
    material/svg/settings-voice.svg
    material/svg/share.svg
    material/svg/shopping-basket.svg
    material/svg/shopping-cart.svg
    material/svg/shop.svg
    material/svg/shop-two.svg
    material/svg/short-text.svg
    material/svg/show-chart.svg
    material/svg/shuffle.svg
    material/svg/signal-cellular-0-bar.svg
    material/svg/signal-cellular-1-bar.svg
    material/svg/signal-cellular-2-bar.svg
    material/svg/signal-cellular-3-bar.svg
    material/svg/signal-cellular-4-bar.svg
    material/svg/signal-cellular-connected-no-internet-0_bar.svg
    material/svg/signal-cellular-connected-no-internet-1_bar.svg
    material/svg/signal-cellular-connected-no-internet-2_bar.svg
    material/svg/signal-cellular-connected-no-internet-3_bar.svg
    material/svg/signal-cellular-connected-no-internet-4_bar.svg
    material/svg/signal-cellular-no-sim.svg
    material/svg/signal-cellular-null.svg
    material/svg/signal-cellular-off.svg
    material/svg/signal-wifi-0-bar.svg
    material/svg/signal-wifi-1-bar-lock.svg
    material/svg/signal-wifi-1-bar.svg
    material/svg/signal-wifi-2-bar-lock.svg
    material/svg/signal-wifi-2-bar.svg
    material/svg/signal-wifi-3-bar-lock.svg
    material/svg/signal-wifi-3-bar.svg
    material/svg/signal-wifi-4-bar-lock.svg
    material/svg/signal-wifi-4-bar.svg
    material/svg/signal-wifi-off.svg
    material/svg/sim-card-alert.svg
    material/svg/sim-card.svg
    material/svg/skip-next.svg
    material/svg/skip-previous.svg
    material/svg/slideshow.svg
    material/svg/slow-motion-video.svg
    material/svg/smartphone.svg
    material/svg/smoke-free.svg
    material/svg/smoking-rooms.svg
    material/svg/sms-failed.svg
    material/svg/sms.svg
    material/svg/snooze.svg
    material/svg/sort.svg
    material/svg/space-bar.svg
    material/svg/spa.svg
    material/svg/speaker-group.svg
    material/svg/speaker-notes-off.svg
    material/svg/speaker-notes.svg
    material/svg/speaker-phone.svg
    material/svg/speaker.svg
    material/svg/spellcheck.svg
    material/svg/star-half.svg
    material/svg/stars.svg
    material/svg/stay-current-landscape.svg
    material/svg/stay-current-portrait.svg
    material/svg/stay-primary-landscape.svg
    material/svg/stay-primary-portrait.svg
    material/svg/stop-screen-share.svg
    material/svg/stop.svg
    material/svg/storage.svg
    material/svg/store-mall-directory.svg
    material/svg/store.svg
    material/svg/straighten.svg
    material/svg/streetview.svg
    material/svg/strikethrough-s.svg
    material/svg/style.svg
    material/svg/subdirectory-arrow-left.svg
    material/svg/subdirectory-arrow-right.svg
    material/svg/subject.svg
    material/svg/subscriptions.svg
    material/svg/subtitles.svg
    material/svg/subway.svg
    material/svg/supervisor-account.svg
    material/svg/surround-sound.svg
    material/svg/swap-calls.svg
    material/svg/swap-horiz.svg
    material/svg/swap-vertical-circle.svg
    material/svg/swap-vert.svg
    material/svg/switch-camera.svg
    material/svg/switch-video.svg
    material/svg/sync-disabled.svg
    material/svg/sync-problem.svg
    material/svg/sync.svg
    material/svg/system-update-alt.svg
    material/svg/system-update.svg
    material/svg/tablet-android.svg
    material/svg/tablet-mac.svg
    material/svg/tablet.svg
    material/svg/tab.svg
    material/svg/tab-unselected.svg
    material/svg/tag-faces.svg
    material/svg/tap-and-play.svg
    material/svg/terrain.svg
    material/svg/text-fields.svg
    material/svg/text-format.svg
    material/svg/textsms.svg
    material/svg/texture.svg
    material/svg/theaters.svg
    material/svg/thumb-down.svg
    material/svg/thumbs-up-down.svg
    material/svg/thumb-up.svg
    material/svg/timelapse.svg
    material/svg/timeline.svg
    material/svg/timer-10.svg
    material/svg/timer-3.svg
    material/svg/timer-off.svg
    material/svg/timer.svg
    material/svg/time-to-leave.svg
    material/svg/title.svg
    material/svg/toc.svg
    material/svg/today.svg
    material/svg/toll.svg
    material/svg/tonality.svg
    material/svg/touch-app.svg
    material/svg/toys.svg
    material/svg/track-changes.svg
    material/svg/traffic.svg
    material/svg/train.svg
    material/svg/tram.svg
    material/svg/transfer-within-a-station.svg
    material/svg/transform.svg
    material/svg/translate.svg
    material/svg/trending-down.svg
    material/svg/trending-flat.svg
    material/svg/trending-up.svg
    material/svg/tune.svg
    material/svg/turned-in-not.svg
    material/svg/turned-in.svg
    material/svg/tv.svg
    material/svg/unarchive.svg
    material/svg/undo.svg
    material/svg/unfold-less.svg
    material/svg/unfold-more.svg
    material/svg/update.svg
    material/svg/usb.svg
    material/svg/verified-user.svg
    material/svg/vertical-align-bottom.svg
    material/svg/vertical-align-center.svg
    material/svg/vertical-align-top.svg
    material/svg/vibration.svg
    material/svg/video-call.svg
    material/svg/videocam-off.svg
    material/svg/videocam.svg
    material/svg/videogame-asset.svg
    material/svg/video-label.svg
    material/svg/video-library.svg
    material/svg/view-agenda.svg
    material/svg/view-array.svg
    material/svg/view-carousel.svg
    material/svg/view-column.svg
    material/svg/view-comfy.svg
    material/svg/view-compact.svg
    material/svg/view-day.svg
    material/svg/view-headline.svg
    material/svg/view-list.svg
    material/svg/view-module.svg
    material/svg/view-quilt.svg
    material/svg/view-stream.svg
    material/svg/view-week.svg
    material/svg/visibility-off.svg
    material/svg/visibility.svg
    material/svg/voice-chat.svg
    material/svg/voicemail.svg
    material/svg/volume-down.svg
    material/svg/volume-mute.svg
    material/svg/volume-off.svg
    material/svg/volume-up.svg
    material/svg/vpn-key.svg
    material/svg/vpn-lock.svg
    material/svg/wallpaper.svg
    material/svg/warning.svg
    material/svg/watch-later.svg
    material/svg/watch.svg
    material/svg/wb-auto.svg
    material/svg/wb-cloudy.svg
    material/svg/wb-incandescent.svg
    material/svg/wb-iridescent.svg
    material/svg/wb-sunny.svg
    material/svg/wc.svg
    material/svg/web-asset.svg
    material/svg/web.svg
    material/svg/weekend.svg
    material/svg/whatshot.svg
    material/svg/widgets.svg
    material/svg/wifi-lock.svg
    material/svg/wifi.svg
    material/svg/wifi-tethering.svg
    material/svg/work.svg
    material/svg/wrap-text.svg
    material/svg/youtube-searched-for.svg
    material/svg/zoom-out-map.svg
)
