INSERT INTO crosswords (awake, label, questions) VALUES (
    'g05 8/8 pp. 14-19',
    'Despertai! Agosto — 2005',
    '{
        "0h": {"number": 1, "question": "Filho e sucessor do Rei Jeú de Israel.", "verse": "2 Reis 10:35", "answer": "JEOACAZ"},
        "8h": {"number": 3, "question": "Oficial da corte que informou Assuero sobre o madeiro que Hamã fez para Mordecai.", "verse": "Ester 7:9", "answer": "HARBONA"},
        "32h": {"number": 5, "question": "Príncipe encarregado da família palaciana de Salomão.", "verse": "1 Reis 4:2, 6", "answer": "AISAR"},
        "38h": {"number": 7, "question": "Irrigar; molhar.", "verse": "Gênesis 2:10", "answer": "REGAR"},
        "62h": {"number": 10, "question": "Além dos irmãos Tiago, José, Judas e Simão, Jesus também tinha...", "verse": "Marcos 6:3", "answer": "IRMAS"},
        "68h": {"number": 12, "question": "Irmã de Moisés.", "verse": "Números 26:59", "answer": "MIRIA"},
        "90h": {"number": 13, "question": "Alimento energizante utilizado por João, o Batizador.", "verse": "Mateus 3:1, 4", "answer": "MEL"},
        "94h": {"number": 14, "question": "Nono filho de Jacó e o quinto dos sete de Léia.", "verse": "Gênesis 35:23", "answer": "ISSACAR"},
        "102h": {"number": 15, "question": "Escritor do Salmo 89", "verse": "Salmo 89:0", "answer": "ETA"},
        "120h": {"number": 16, "question": "Mãe do profeta Samuel.", "verse": "1 Samuel 1:20", "answer": "ANA"},
        "124h": {"number": 18, "question": "Cidade cananeia capturada e destruída por Josué.", "verse": "Josué 10:28", "answer": "MAQUEDA"},
        "132h": {"number": 20, "question": "Apedrejado junto com sua família por ter roubado a Jeová.", "verse": "Josué 7:20, 21", "answer": "ACA"},
        "152h": {"number": 22, "question": "O último inimigo.", "verse": "1 Coríntios 15:26", "answer": "MORTE"},
        "158h": {"number": 23, "question": "Chefe do exército de Absalão, por ocasião da sua revolta contra Davi.", "verse": "2 Samuel 17:25", "answer": "AMASA"},
        "182h": {"number": 24, "question": "Filho de Ló com sua filha mais velha.", "verse": "Gênesis 19:37", "answer": "MOABE"},
        "188h": {"number": 26, "question": "Pedra central da terceira fileira do peitoral de Arão.", "verse": "Êxodo 28:15, 19", "answer": "AGATA"},
        "210h": {"number": 27, "question": "Esposa de Arão.", "verse": "Êxodo 6:23", "answer": "ELISEBA"},
        "218h": {"number": 28, "question": "Segundo príncipe mencionado como enviado por Jeosafá para ensinar a lei de Jeová nas cidades de Judá.", "verse": "2 Crônicas 17:7, 9", "answer": "OBADIAS"},
        "0v": {"number": 1, "question": "Rei de Judá, filho de Jeoiaquim, levado ao exílio em Babilônia.", "verse": "2 Reis 24:6, 15", "answer": "JOAQUIM"},
        "6v": {"number": 2, "question": "Pai da midianita Cosbi, morta por Finéias.", "verse": "Números 25:15", "answer": "ZUR"},
        "8v": {"number": 3, "question": "Monte onde Arão faleceu.", "verse": "Deuteronômio 32:50", "answer": "HOR"},
        "14v": {"number": 4, "question": "Nação que conquistou o reino setentrional de Israel em 740 AEC.", "verse": "2 Reis 17:5, 6", "answer": "ASSIRIA"},
        "32v": {"number": 5, "question": "Nome secreto dado a Jerusalém em Isaías 29:1, 2, 7.", "verse": "Isaías 29:1, 2, 7", "answer": "ARIEL"},
        "34v": {"number": 6, "question": "Amaldiçoou Davi e atirou pedras nele quando ele fugia de Absalão.", "verse": "2 Samuel 16:5-8", "answer": "SIMEI"},
        "40v": {"number": 8, "question": "Os pastores dessa região contenderam com os de Isaque por água.", "verse": "Gênesis 26:20", "answer": "GERAR"},
        "42v": {"number": 9, "question": "Prostituta de Jericó que se tornou adoradora de Jeová.", "verse": "Josué 2:1", "answer": "RAABE"},
        "66v": {"number": 11, "question": "Rei egípcio que despojou Jerusalém de seus tesouros nos dias de Roboão.", "verse": "2 Crônicas 12:2, 9", "answer": "SISAQUE"},
        "68v": {"number": 12, "question": "Caverna que serviu de sepulcro para a família de Abraão.", "verse": "Gênesis 25:8, 9", "answer": "MACPELA"},
        "120v": {"number": 16, "question": "Salomão baniu Abiatar para essa cidade.", "verse": "1 Reis 2:26", "answer": "ANATOTE"},
        "122v": {"number": 17, "question": "Cidade levita designada aos filhos de Arão, nos dias de Josué.", "verse": "Josué 21:18", "answer": "ALMOM"},
        "124v": {"number": 18, "question": "Terra onde Abraão deveria oferecer Isaque como sacrifício.", "verse": "Gênesis 22:2", "answer": "MORIA"},
        "130v": {"number": 19, "question": "Em Romanos 15:26, Paulo fala da generosidade dos cristãos dessa província.", "verse": "Romanos 15:26", "answer": "ACAIA"},
        "132v": {"number": 20, "question": "Um dos rios de Damasco, mencionado por Naamã.", "verse": "2 Reis 5:12", "answer": "ABANA"},
        "134v": {"number": 21, "question": "Nome hebraico de Abednego.", "verse": "Daniel 1:6, 7", "answer": "AZARIAS"},
        "186v": {"number": 25, "question": "Filho de Baasa e quarto rei das dez tribos de Israel, morto por Zinri.", "verse": "1 Reis 16:8-10", "answer": "ELA"},
        "188v": {"number": 26, "question": "Irmão de Uzá que andava na frente da carroça que transportava a arca quando Uzá foi golpeado.", "verse": "2 Samuel 6:3, 4", "answer": "AIO"}
    }'
) ON CONFLICT(awake) DO UPDATE SET label = excluded.label, questions = excluded.questions;
-- ;

INSERT INTO crosswords (awake, label, questions) VALUES (
    'g05 8/2 pp. 21-27',
    'Despertai! Fevereiro — 2005',
    '{
        "0h": {"number": 1, "question": "Sucessor do profeta Elias.", "verse": "1 Reis 19:16, 19", "answer": "ELISEU"},
        "9h": {"number": 4, "question": "Mulher por quem Sansão se enamorou.", "verse": "Juízes 16:3, 4", "answer": "DALILA"},
        "21h": {"number": 7, "question": "São citadas como esplendor dos anciãos em Provérbios 20:29.", "verse": "Provérbios 20:29", "answer": "CAS"},
        "45h": {"number": 10, "question": "Filho de Azalias e secretário da corte, a quem Hilquias entregou o livro da lei encontrado no templo.", "verse": "2 Reis 22:3, 8", "answer": "SAFA"},
        "50h": {"number": 11, "question": "Língua em que se escreveu originalmente as Escrituras Cristãs, com exceção do evangelho de Mateus, que foi escrito primeiramente em hebraico.", "verse": "", "answer": "GREGO"},
        "56h": {"number": 12, "question": "Guerreiro geteu que foi leal a Davi quando este fugia de Jerusalém devido à rebelião de Absalão.", "verse": "2 Samuel 15:14-22", "answer": "ITAI"},
        "77h": {"number": 13, "question": "Nome de um lugar que tinha uma grande cisterna, onde Saul indagou sobre o paradeiro de Davi e Samuel.", "verse": "1 Samuel 19:22", "answer": "SECU"},
        "84h": {"number": 15, "question": "Deus grego que o povo de Listra identificou com Barnabé, por ocasião da cura de um homem coxo.", "verse": "Atos 14:8-13", "answer": "ZEUS"},
        "105h": {"number": 19, "question": "Neto de Arão que traspassou Zinri e Cosbi com uma lança, por ‘não tolerar rivalidade para com Jeová’.", "verse": "Números 25:6-8, 11, 14, 15", "answer": "FINEIAS"},
        "113h": {"number": 20, "question": "Etapa final da separação dos grãos de cereais, tais como a cevada e o trigo, de sua palha e haste.", "verse": "Jeremias 4:11; Mateus 3:12", "answer": "JOEIRAR"},
        "137h": {"number": 23, "question": "Profeta de Jeová que incentivou os israelitas a ‘rasgar os corações e não as vestes, e retornar a Jeová’.", "verse": "Joel 1:1; 2:13", "answer": "JOEL"},
        "144h": {"number": 25, "question": "Moisés ordenou que matassem cada israelita que tivesse ligação com esse deus falso.", "verse": "Números 25:4, 5", "answer": "BAAL"},
        "165h": {"number": 27, "question": "Forma comum de livro durante o período de escrita da Bíblia.", "verse": "Jeremias 36:28; Gálatas 3:10", "answer": "ROLO"},
        "170h": {"number": 29, "question": "Jeová ordenou que Jacó morasse nesse lugar logo após Diná ser desonrada.", "verse": "Gênesis 34:1, 2, 30-Gên 35:1", "answer": "BETEL"},
        "176h": {"number": 30, "question": "Quando Sodoma e Gomorra estavam prestes a ser destruídas, Ló solicitou a Jeová e obteve permissão de fugir para essa cidade.", "verse": "Gênesis 19:18-23", "answer": "ZOAR"},
        "201h": {"number": 31, "question": "A perspicácia do homem o torna menos propenso a manifestar o quê?", "verse": "Provérbios 19:11", "answer": "IRA"},
        "210h": {"number": 32, "question": "Primeiro juiz citado por nome depois de Josué.", "verse": "Juízes 3:9", "answer": "OTNIEL"},
        "219h": {"number": 33, "question": "Único filho de Abraão com Sara.", "verse": "Gênesis 21:3", "answer": "ISAQUE"},
        "0v": {"number": 1, "question": "Cristão que ajudava Paulo e que foi enviado à Macedônia, junto com Timóteo.", "verse": "Atos 19:21, 22", "answer": "ERASTO"},
        "3v": {"number": 2, "question": "A rainha desse reino visitou Salomão.", "verse": "1 Reis 10:1", "answer": "SABA"},
        "7v": {"number": 3, "question": "Profissional egípcio morto durante a celebração de aniversário de Faraó.", "verse": "Gênesis 40:20-22", "answer": "PADEIRO"},
        "11v": {"number": 5, "question": "Terceiro filho de Jacó com sua esposa Léia.", "verse": "Gênesis 35:23", "answer": "LEVI"},
        "14v": {"number": 6, "question": "Judeu amigo de Paulo que trabalhava com ele na fabricação de tendas.", "verse": "Atos 18:1-3", "answer": "AQUILA"},
        "35v": {"number": 8, "question": "Profeta que atuava em Jerusalém e Judá na época em que Zorobabel era governador.", "verse": "Ageu 1:1", "answer": "AGEU"},
        "39v": {"number": 9, "question": "Judeu, adorador de Jeová, que resgatou Rute e teve com ela um filho, que se tornou avô de Davi.", "verse": "Rute 2:19, 20; 4:10, 13, 17", "answer": "BOAZ"},
        "78v": {"number": 14, "question": "Cidade que no primeiro século era o centro da adoração de Ártemis.", "verse": "Atos 19:26-28", "answer": "EFESO"},
        "86v": {"number": 16, "question": "Profeta de Jeová que fugiu para o Egito ao saber que Jeoiaquim queria matá-lo, mas que foi levado de volta e morto.", "verse": "Jeremias 26:20-23", "answer": "URIJA"},
        "91v": {"number": 17, "question": "Doze israelitas espiaram a Terra Prometida partindo desse ermo.", "verse": "Números 13:21", "answer": "ZIM"},
        "103v": {"number": 18, "question": "Sob a Lei mosaica toda oferta de cereais tinha de ser apresentada com essa substância.", "verse": "Levítico 2:13", "answer": "SAL"},
        "127v": {"number": 21, "question": "Uma das esposas de Abraão, mãe de seis filhos.", "verse": "Gênesis 25:1, 2", "answer": "QUETURA"},
        "135v": {"number": 22, "question": "Primeira cidade cananeia conquistada pelos israelitas.", "verse": "Josué 6:1, 24", "answer": "JERICO"},
        "140v": {"number": 24, "question": "Esse animal é retratado como estando em paz com o cordeiro durante o reinado do Messias.", "verse": "Isaías 11:6", "answer": "LOBO"},
        "144v": {"number": 25, "question": "Serva de Raquel e esposa secundária de Jacó.", "verse": "Gênesis 30:3, 7", "answer": "BILA"},
        "149v": {"number": 26, "question": "Monte onde o anjo de Jeová apareceu a Moisés no meio dum espinheiro em fogo.", "verse": "Êxodo 3:1, 2", "answer": "HOREBE"},
        "168v": {"number": 28, "question": "Rei de Israel, avô de Atalia.", "verse": "2 Reis 8:26", "answer": "ONRI"},
        "176v": {"number": 30, "question": "Servo da casa de Saul, a quem Davi designou para cuidar da herança de Mefibosete.", "verse": "2 Samuel 9:2, 3, 8-10", "answer": "ZIBA"}
    }'
) ON CONFLICT(awake) DO UPDATE SET label = excluded.label, questions = excluded.questions;
-- ;

INSERT INTO crosswords (awake, label, questions) VALUES (
    'g05 8/4 pp. 12-19',
    'Despertai! Abril — 2005',
    '{
        "0h": {"number": 1, "question": "Horonita que se opôs aos esforços de Neemias de recuperar a muralha de Jerusalém.", "verse": "Neemias 2:10", "answer": "SAMBALA"},
        "8h": {"number": 4, "question": "Como água fresca para a alma cansada é a ... boa de uma terra longínqua.", "verse": "Provérbios 25:25", "answer": "NOTICIA"},
        "30h": {"number": 7, "question": "Formato comum dos livros durante a escrita da Bíblia.", "verse": "Apocalipse 20:12", "answer": "ROLOS"},
        "40h": {"number": 9, "question": "Um dos discípulos de João, o Batizador.", "verse": "João 1:35, 40", "answer": "ANDRE"},
        "62h": {"number": 10, "question": "Em troca de alguns destes frutos, Raquel deixou que sua irmã tivesse relações sexuais com Jacó.", "verse": "Gênesis 30:14, 15", "answer": "MANDRAGORAS"},
        "90h": {"number": 11, "question": "Termo de honra proclamado diante de José quando Faraó designou-o como o segundo em seu reino.", "verse": "Gênesis 41:43", "answer": "AVREQUE"},
        "98h": {"number": 12, "question": "Elemento utilizado por Jeová, junto com fogo, para destruir Sodoma e Gomorra.", "verse": "Gênesis 19:24", "answer": "ENXOFRE"},
        "120h": {"number": 13, "question": "Caverna que serviu de sepultura para Sara, Abraão e outros.", "verse": "Gênesis 23:19; 25:8, 9; 49:30, 31, 33; 50:7, 13", "answer": "MACPELA"},
        "128h": {"number": 15, "question": "Desejar ardentemente, ansiar.", "verse": "Deuteronômio 12:20", "answer": "ALMEJAR"},
        "152h": {"number": 17, "question": "Tentativa de prever o futuro por meios sobrenaturais; ação de adivinhar.", "verse": "Deuteronômio 18:10", "answer": "ADIVINHACAO"},
        "180h": {"number": 19, "question": "Material que Moisés usou para fazer a cobra ardente.", "verse": "Números 21:8, 9", "answer": "COBRE"},
        "190h": {"number": 20, "question": "Filho de Boaz e Rute, antepassado de Davi.", "verse": "Rute 4:13, 21, 22", "answer": "OBEDE"},
        "210h": {"number": 21, "question": "Personagem que, junto com seu irmão Adrameleque, matou seu pai Senaqueribe.", "verse": "2 Reis 19:36, 37", "answer": "SAREZER"},
        "218h": {"number": 22, "question": "Produto de certa árvore, oferecido por astrólogos ao menino Jesus.", "verse": "Mateus 2:11", "answer": "OLIBANO"},
        "0v": {"number": 1, "question": "Uma das forças usadas por Jeová para cumprir sua palavra.", "verse": "Salmo 148:8", "answer": "SARAIVA"},
        "2v": {"number": 2, "question": "Marido de Rute, filho de Elimeleque e Noemi.", "verse": "Rute 1:2; 4:10", "answer": "MALOM"},
        "6v": {"number": 3, "question": "Sacola de couro usada por viajantes.", "verse": "Mateus 10:10", "answer": "ALFORJE"},
        "8v": {"number": 4, "question": "Um dos filhos de Davi, nascido em Jerusalém.", "verse": "2 Samuel 5:13-15", "answer": "NEFEGUE"},
        "12v": {"number": 5, "question": "Local do acampamento dos israelitas enquanto aguardavam os 12 espias.", "verse": "Números 13:25, 26", "answer": "CADES"},
        "14v": {"number": 6, "question": "Esposa de José, mãe de Manassés e de Efraim.", "verse": "Gênesis 46:20", "answer": "ASENATE"},
        "34v": {"number": 8, "question": "Governante assírio que enviou cartas ameaçadoras a Ezequias.", "verse": "Isaías 37:14, 17", "answer": "SENAQUERIBE"},
        "40v": {"number": 9, "question": "Ato de se aproximar, avizinhação.", "verse": "Romanos 5:2", "answer": "APROXIMACAO"},
        "120v": {"number": 13, "question": "Animais importados por Salomão.", "verse": "1 Reis 10:22", "answer": "MACACOS"},
        "126v": {"number": 14, "question": "Filho do sumo sacerdote Aimeleque, único a escapar de Doegue, o edomita.", "verse": "1 Samuel 22:16, 20", "answer": "ABIATAR"},
        "128v": {"number": 15, "question": "Alienado, apartado.", "verse": "Números 14:34", "answer": "ALHEADO"},
        "134v": {"number": 16, "question": "Jeová é meu ...  e minha fortaleza.", "verse": "Salmo 18:2", "answer": "ROCHEDO"},
        "152v": {"number": 17, "question": "Um dos homens que o rei Josias enviou à profetisa Hulda para saber o que fazer com o recém-encontrado livro da lei.", "verse": "2 Reis 22:12-14", "answer": "ACBOR"},
        "162v": {"number": 18, "question": "Última letra do alfabeto grego.", "verse": "Apocalipse 1:8", "answer": "OMEGA"}
    }'
) ON CONFLICT(awake) DO UPDATE SET label = excluded.label, questions = excluded.questions;
-- ;

INSERT INTO crosswords (awake, label, questions) VALUES (
    'g05 8/12 pp. 19-22',
    'Despertai! Dezembro — 2005',
    '{
        "1h": {"number": 1, "question": "", "verse": "", "answer": "CUTELO"},
        "8h": {"number": 4, "question": "", "verse": "", "answer": "ARAUNA"},
        "30h": {"number": 9, "question": "", "verse": "", "answer": "ASIMA"},
        "36h": {"number": 10, "question": "", "verse": "", "answer": "SIM"},
        "40h": {"number": 12, "question": "", "verse": "", "answer": "SIENE"},
        "60h": {"number": 13, "question": "", "verse": "", "answer": "COSTURA"},
        "68h": {"number": 14, "question": "", "verse": "", "answer": "NEEMIAS"},
        "92h": {"number": 15, "question": "", "verse": "", "answer": "NILO"},
        "99h": {"number": 17, "question": "", "verse": "", "answer": "BOAZ"},
        "111h": {"number": 19, "question": "", "verse": "", "answer": "ONA"},
        "122h": {"number": 21, "question": "", "verse": "", "answer": "AGAR"},
        "129h": {"number": 23, "question": "", "verse": "", "answer": "CAIM"},
        "150h": {"number": 28, "question": "", "verse": "", "answer": "BARNABÉ"},
        "158h": {"number": 30, "question": "", "verse": "", "answer": "INCENSO"},
        "180h": {"number": 32, "question": "", "verse": "", "answer": "BRACO"},
        "186h": {"number": 33, "question": "", "verse": "", "answer": "ASA"},
        "190h": {"number": 34, "question": "", "verse": "", "answer": "NEREU"},
        "211h": {"number": 35, "question": "", "verse": "", "answer": "REBECA"},
        "218h": {"number": 36, "question": "", "verse": "", "answer": "TRONOS"},
        "2v": {"number": 2, "question": "", "verse": "", "answer": "UZIAS"},
        "4v": {"number": 3, "question": "", "verse": "", "answer": "EMANUEL"},
        "10v": {"number": 5, "question": "", "verse": "", "answer": "ASSUERO"},
        "12v": {"number": 6, "question": "", "verse": "", "answer": "NOEMI"},
        "15v": {"number": 7, "question": "", "verse": "", "answer": "CARCOR"},
        "29v": {"number": 8, "question": "", "verse": "", "answer": "GERSON"},
        "36v": {"number": 10, "question": "", "verse": "", "answer": "SEAS"},
        "38v": {"number": 11, "question": "", "verse": "", "answer": "MENE"},
        "92v": {"number": 15, "question": "", "verse": "", "answer": "NOA"},
        "97v": {"number": 16, "question": "", "verse": "", "answer": "ANA"},
        "102v": {"number": 18, "question": "", "verse": "", "answer": "ZIM"},
        "120v": {"number": 20, "question": "", "verse": "", "answer": "HOBABE"},
        "124v": {"number": 22, "question": "", "verse": "", "answer": "ANATOTE"},
        "130v": {"number": 24, "question": "", "verse": "", "answer": "ARCANJO"},
        "134v": {"number": 25, "question": "", "verse": "", "answer": "ENOQUE"},
        "141v": {"number": 26, "question": "", "verse": "", "answer": "BELA"},
        "143v": {"number": 27, "question": "", "verse": "", "answer": "CITA"},
        "152v": {"number": 29, "question": "", "verse": "", "answer": "RAABE"},
        "162v": {"number": 31, "question": "", "verse": "", "answer": "NARDO"}
    }'
) ON CONFLICT(awake) DO UPDATE SET label = excluded.label, questions = excluded.questions;
