name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: Build and test (Qt 6.8.0)
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
      CC: gcc
      CXX: g++
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \ 
            build-essential \ 
            ninja-build \ 
            lcov \ 
            libgl1-mesa-dev \ 
            libglu1-mesa-dev \ 
            libxkbcommon-x11-0 \ 
            libfontconfig1 \ 
            libdbus-1-3 \ 
            libxcb-icccm4 \ 
            libxcb-image0 \ 
            libxcb-keysyms1 \ 
            libxcb-randr0 \ 
            libxcb-render-util0 \ 
            libxcb-shape0 \ 
            libxcb-xfixes0 \ 
            libxcb1

      - name: Set up Qt 6.8.0
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          host: linux
          arch: gcc_64
          modules: qtdeclarative qtsql
          cache: true

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=ON \
            -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Run unit tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Generate coverage report
        run: cmake --build build --target Crosswords_coverage_run

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-6.8.0
          path: |
            build/coverage/Crosswords.info
            build/coverage/Crosswords_filtered.info
            build/coverage/Crosswords_report
          if-no-files-found: warn
